title:             Sid's Blog
email:             your-email@example.com
description:       A Blog by Pandiri Siddhardha
author:            Start Bootstrap
baseurl:           "/blog"
url:               "https://pandirisid.github.io"

# Social Profiles
twitter_username:  PandiriSid
github_username:   PandiriSid
facebook_username: PandiriSiddhardha

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
